#!/usr/bin/env bash
# Installs nginx and sets up a custom index page

apt-get update -y
apt-get install nginx -y

# Set the correct web root directory
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html

# Restart nginx using service (not systemctl)
service nginx restart

